version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: kosy9/chatbot:first_attempt
    expose: 
      - "5055"